repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.88.1
  hooks:
    - id: terraform_fmt
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
