{
 "title": "VM (Base Metal) Stats",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Containers in DigitalOcean VM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DO Containers CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id !=\"/\", id !=\"/docker\", id !~\"/system.*\", id !=\"Value\", name!=\"\"}[2m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DO Containers CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{id !=\"/\", id !=\"/docker\", id !~\"/system.*\", id !=\"Value\", name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",}[2m])) by (instance, job)) * 100",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Memory Usage (in %)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{} * 100) / node_memory_MemTotal_bytes{})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage (in Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{} \n    - node_memory_MemFree_bytes{} \n    - node_memory_Buffers_bytes{} \n    - node_memory_Cached_bytes{}\n    - node_memory_SReclaimable_bytes{}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}